#!/usr/bin/env python3
"""Cut the top navbar out of AdminLTE 3 for the one PFAS topbar (GAPS §93,
DECISIONS 2026-10-03 "One top toolbar").

AdminLTE (MIT, github.com/ColorlibHQ/AdminLTE) is built on Bootstrap 4.6 --
the same major version as SENAITE core -- so its `main-header` navbar is the
pattern core's own toolbar already follows. PFAS pages do not load Bootstrap,
so the rules the navbar needs (Bootstrap's .navbar / .nav-link / dropdown and
AdminLTE's .main-header) are copied here, every selector scoped under
`.pfas-topbar` so nothing leaks onto core's own markup.

    python3 tools/vendor_adminlte_topbar.py adminlte.css \
        > src/senaite/pfas/browser/static/vendor/adminlte-topbar-3.2.0.css

Input: admin-lte@3.2.0 dist/css/adminlte.css (npm / jsDelivr). The licence is
shipped next to the output as adminlte-LICENSE.txt.
"""
import re
import sys

import tinycss2

ROOT = "pfas-topbar"
# Classes the topbar element itself carries: a selector starting with one of
# them is joined to the scope (".pfas-topbar.navbar"), not nested under it.
ROOT_CLASSES = ("main-header", "navbar", "navbar-expand", "navbar-dark")
KEEP = re.compile(r"^\.(main-header|navbar|navbar-expand|navbar-dark|navbar-nav|nav-link|"
                  r"nav-item|dropdown|dropdown-menu|dropdown-menu-right|dropdown-menu-lg|"
                  r"dropdown-item|dropdown-divider|dropdown-header|dropdown-toggle|"
                  r"navbar-badge|navbar-brand)\b")
DROP = re.compile(r"dark-mode|text-sm|layout-|sidebar|legacy|control-|navbar-light|"
                  r"navbar-white|navbar-(primary|secondary|info|success|warning|danger|"
                  r"gray|lightblue|navy|olive|lime|fuchsia|maroon|blue|indigo|purple|pink|"
                  r"red|orange|yellow|green|teal|cyan|white|dark-)|accent-|"
                  r"navbar-expand-(sm|md|lg|xl)|navbar-toggler|navbar-collapse|navbar-text|"
                  r"dropdown-menu-(sm|xl|left)|dropleft|dropright|dropup|nav-pills|nav-tabs")


def scope(sel):
    sel = sel.strip()
    first = re.match(r"\.([\w-]+)", sel).group(1)
    if first in ROOT_CLASSES:
        return "." + ROOT + sel
    return "." + ROOT + " " + sel


def wanted(sel):
    sel = sel.strip()
    return bool(KEEP.match(sel)) and not DROP.search(sel)


def rules(nodes, out, media=None):
    for node in nodes:
        if node.type == "qualified-rule":
            sels = [s for s in tinycss2.serialize(node.prelude).split(",") if s.strip()]
            keep = [scope(s) for s in sels if wanted(s)]
            if not keep:
                continue
            body = tinycss2.serialize(node.content).strip()
            text = ",\n".join(keep) + " {\n  " + body + "\n}\n"
            out.append((media, text))
        elif node.type == "at-rule" and node.lower_at_keyword == "media":
            inner = tinycss2.parse_rule_list(node.content, skip_comments=True,
                                             skip_whitespace=True)
            rules(inner, out, tinycss2.serialize(node.prelude).strip())


def main(path):
    with open(path, encoding="utf-8") as fh:
        sheet = tinycss2.parse_stylesheet(fh.read(), skip_comments=True, skip_whitespace=True)
    out = []
    rules(sheet, out)
    print("/*! AdminLTE v3.2.0 (MIT, Copyright 2014-2021 ColorlibHQ) and the Bootstrap\n"
          " * v4.6.1 rules it bundles (MIT, Copyright 2011-2021 The Bootstrap Authors,\n"
          " * Twitter, Inc.): the top navbar only, every selector scoped under\n"
          " * ." + ROOT + ". Generated by tools/vendor_adminlte_topbar.py; do not edit.\n"
          " * Licence: adminlte-LICENSE.txt */")
    for media, text in out:
        if media:
            print("@media " + media + " {\n" + text + "}")
        else:
            print(text)


if __name__ == "__main__":
    main(sys.argv[1])
